baseURL: https://xicu.info
title: Xicu Marí
theme: 
  - hugo-adobe-pdf-embed
  - hugo-shortcode-gallery
  - PaperMod


enableEmoji: true
enableRobotsTXT: true

params:
  env: production
  keywords: [Blog, Portfolio, Electronic Engineer, Robotics, Embedded Systems, Software Development, FPGA]

  adobeClientId: d4ab997cffc5481fb4699cc548b3e9b5

  profileMode:
    enabled: true
    imageUrl: home/profile.png
    imageWidth: 140
    imageHeight: 140

  label:
    iconLight: icons/logo-light.png
    iconDark: icons/logo-dark.png
    iconHeight: 44

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  # Favicons
  assets:
    favicon: icons/favicon.ico
    favicon16x16: icons/favicon-16x16.png
    favicon32x32: icons/favicon-32x32.png
    apple_touch_icon: icons/apple-touch-icon.png
    
  # Social Icons
  socialIcons:
  - name: Email
    url: mailto:hello@xicu.info
  - name: LinkedIn
    url: https://www.linkedin.com/in/xicu
  - name: Github
    url: https://github.com/XicuM
  - name: Instagram
    url: https://www.instagram.com/xicu.m

# Language configuration
defaultContentLanguage: en
defaultContentLanguageInSubdir: true

# Goldmark configuration
# markup:
#   goldmark:
#     renderer:
#       unsafe: true
#   renderHooks:
#       image:
#         enableDefault: true