baseURL: https://xicu.info
title: Xicu Marí
theme: 
  - hugo-adobe-pdf-embed
  - hugo-shortcode-gallery
  - PaperMod

enableEmoji: true
enableRobotsTXT: true

params:
  description: I'm Xicu, an Electronic Engineer passionate about Robotics, Software Development and Philosophy. Here you will find my blog, projects and more. Enjoy your stay!
  env: production
  defaultTheme: auto
  keywords: [Blog, Portfolio, Electronic Engineer, Robotics, Embedded Systems, Software Development, FPGA]

  # Adobe Embed PDF (Production)
  adobeClientId: b43ddb4a61184cbb9a808df9f177dc01
  
  # Adobe Embed PDF (Localhost)
  #adobeClientId: 575c9ad6052b4bbead8648193d6d51e2

  profileMode:
    enabled: true
    imageUrl: home/profile.png
    imageWidth: 140
    imageHeight: 140

  cover:
    linkFullImages: true

  label:
    iconLight: icons/logo-light.png
    iconDark: icons/logo-dark.png
    iconHeight: 44

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  # Favicons
  assets:
    favicon: icons/favicon.ico
    favicon16x16: icons/favicon-16x16.png
    favicon32x32: icons/favicon-32x32.png
    apple_touch_icon: icons/apple-touch-icon.png

# Language configuration
defaultContentLanguage: en
defaultContentLanguageInSubdir: true

# Goldmark configuration
# markup:
#   goldmark:
#     renderer:
#       unsafe: true
#   renderHooks:
#       image:
#         enableDefault: true

markup:

  # Goldmark configuration
  goldmark:
    extensions:
      taskList: true
      table: true
      extras:
        delete:
          enable: false
        insert:
          enable: false
        mark:
          enable: false
        subscript:
          enable: false
        superscript:
          enable: false
      strikethrough: false

  # Code highlighting
  highlight:
    codeFences: true
    lineNos: true
    lineNumbersInTable: true
    noClasses: false

  # Table of contents
  tableOfContents:
    ordered: true