# ----------------------------------------------------------------------
# English

en:
  contentDir: content/en
  disabled: false
  languageCode: "en-US"
  languageName: English
  weight: 1
  params:
    profileMode:
      title: Welcome to my website! 👋
      subtitle: I'm **Xicu**, an Electronic Engineer passionate about Robotics, Software Development and Philosophy. Here you will find my blog, projects and more. Enjoy your stay! 🚀
      buttons:
        - name: About me
          url: /en/bio
        - name: Blog
          url: /en/posts
        - name: Projects
          url: /en/projects
  menu:
    main:
      - identifier: bio
        name: About me
        url: /en/bio
        weight: 1
      - identifier: blog
        name: Blog
        url: /en/posts
        weight: 2
      - identifier: projects
        name: Projects
        url: /en/projects
        weight: 3
      - identifier: contact
        name: Contact
        url: /en/contact
        weight: 4

# ----------------------------------------------------------------------
# Español

es:
  contentDir: content/es
  disabled: false
  languageCode: "es-ES"
  languageName: Español
  weight: 2
  params:
    profileMode:
      title: ¡Bienvenido a mi sitio web! 👋
      subtitle: Soy **Xicu**, un Ingeniero Electrónico apasionado por la Robótica, Desarrollo de Software y Filosofía. Aquí encontrarás mi blog, proyectos y más. ¡Disfruta tu visita! 🚀
      buttons:
      - name: Sobre mí
        url: /es/bio
      - name: Blog
        url: /es/posts
      - name: Proyectos
        url: /es/proyectos
  menu:
    main:
      - identifier: bio
        name: Sobre mí
        url: /es/bio
        weight: 10
      - identifier: blog
        name: Blog
        url: /es/posts
        weight: 20
      - identifier: projects
        name: Proyectos
        url: /es/proyectos
        weight: 30
      - identifier: contact
        name: Contacto
        url: /es/contact
        weight: 40